source 'https://rubygems.org'

gem 'rails', '4.2.1'
gem 'puma'
gem 'pg', '0.20'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'sprockets-rails', '>= 2.3'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'slim'
gem 'bootstrap', '~> 4.0.0.beta2.1'
gem 'jquery-rails'
gem 'react-rails', git: 'https://github.com/reactjs/react-rails.git', branch: 'master'
gem 'webpacker'
gem 'sucker_punch'

group :development, :test do
  gem 'pry-byebug'
  gem 'spring'
  gem 'rspec-rails'
  gem 'factory_bot_rails'
end

gem 'web-console', '~> 2.0', group: :development
